### ISSUE TITLE
Is it possible to change the zeppelin port to someone rather than 8080?

### ISSUE THREAD

**Issue by liudongqing** [SkymindIO/SKIL-CE#36]
I am using it in a public docker server, so I cannot make 8080 available. is there a way to change the port?

**Comment by abhishekpathak** [comment]
As of now, I don't think so. @kepricon can you confirm?

**Comment by wmeddie** [comment]
Wanted to show that it is possible to do this since the 1.1.0 release.

Before starting SKIL for the first time you can set the "Default Zeppelin" port by adding the following line to `/etc/skil/skil-env.sh`

```
export ZEPPELIN_SERVER_PORT=8081
```

Change the 8081 to the port you'd like to use.

You can also change port 8080 in the Docker container but you have to build a new image that exposes the port you want.  Check out the files in the Zip file below to see an example of how to do that.

[skil-ce-8081.zip](https://github.com/SkymindIO/SKIL-CE/files/2612011/skil-ce-8081.zip)
