### ISSUE TITLE
Unable to import a notebook

### ISSUE THREAD

**Issue by ejunprung** [SkymindIO/SKIL-CE#38]
I'm unable to import a Zeppelin notebook. I think the issue might be versions. Will importing a notebook that was generated using a different version of SKIL fail? @wmeddie @kepricon @ShamsUlAzeem 

![screen shot 2018-06-27 at 10 06 30 am](https://user-images.githubusercontent.com/5703667/41988747-f5b14720-79f1-11e8-91a1-6f1694eb8107.png)

**Comment by wmeddie** [comment]
can you try selecting the default zeppelin server instead of leaving it blank.  It looks like it get reset if you dismiss the modal once.

**Comment by ejunprung** [comment]
@wmeddie ah, that fixed it. im so blind...

@slinlee not sure if that's a UI bug up there

**Comment by ejunprung** [comment]
Okay, so this issue happened again. I couldn't reproduce it consistently but I think the issue could be:

1. Default Zeppelin Server is blank.
2. Need to log into Zeppelin first.
3. There's a long lag from when you click "Import Notebook" to when it's actually created. 

I had to try several times to get it to import. I think we should try to fix it b/c our demos rely on this.

**Comment by slinlee** [comment]
k. In the screen shot, I see two errors:
1. The import fails because it can't get the zeppelin server port. This is fixed in Dev already in https://github.com/SkymindIO/lagom-skil-api/pull/1421
2. The error message that is returned isn't JSON, but we try to process it here. I'll file an issue for this.: https://github.com/SkymindIO/lagom-skil-api/blob/e277065ff737f751ad80dad65053de6e83071920/skil-ui-modules/src/main/typescript/dashboard/src/app/workspaces/create-experiment-notebook-btn/create-experiment-notebook-btn.component.ts#L325

UX-wise, I'll make sure the required dropdown controls show that they're required and stop users from submitting malformed data.

**Comment by slinlee** [comment]
@ejunprung btw, what version are you running right now so I can try to re-create this?

**Comment by ejunprung** [comment]
@slinlee I'm using http://skildemo1.southcentralus.cloudapp.azure.com.

SKIL Version 1.0.4
DL4J Version 0.9.2_skil-1.0.0
ND4J Version 0.9.2_skil-1.0.0
Supported Spark Version 1.6.3
Supported Scala Version 2.10

**Comment by slinlee** [comment]
@ejunprung - I'm just writing this down so we don't forget. If we see this again, let's try to get a screenshot of the network panel of the browser console.

Also, the release coming soon includes the change that automatically logs in to zeppelin.
