### ISSUE TITLE
Debian support

### ISSUE THREAD

**Issue by gagatust** [SkymindIO/SKIL-CE#8]
I would like to install SKIL on Debian. How can I do it? Does it exist in the apt-repo?
From docs “Currently the SKIL Community Edition supports the Centos 7 and Redhat 7 operating systems.”

**Comment by raver119** [comment]
It doesn't exist in apt repo atm, but you can use docker images for that.

**Comment by gagatust** [comment]
Thank you. I'll try it.

**Comment by wmeddie** [comment]
Please let us know if you run into any issues.

I've spent the last couple of days creating a docker image, but SKIL doesn't work unless the host OS is also running systemd.  If your host is Debian I believe it should work. (But it doesn't work in a Mac running boot2docker for example).

We will add support for other OSes in the coming months.

**Comment by ghisvail** [comment]
> you can use docker images for that

Where?

**Comment by agibsonccc** [comment]
@ghisvail we are deploying docker images to dockerhub fully supported with instructions in the next release..for now it's a roll your own centos 7 -> install rpm setup. @wmeddie I believe has a working docker file he could post for now.

**Comment by wmeddie** [comment]
If you are feeling adventurous and willing to let me know what goes wrong please give the following dockerfile and scripts a try:

https://gist.github.com/wmeddie/61188d832ad24a66347462bc6d21a68e

**Comment by ghisvail** [comment]
Please correct me if I am wrong, but there are currently no sources for SKIL-CE. It's only distributed as a RPM package to be installed on a compatible OS or via Docker, am I right? If so, then it will be of limited use on my end.

**Comment by agibsonccc** [comment]
@ghisvail Can you tell us how exactly? SKIL itself is our proprietary product (see the namespace). That's to be expected. Like any other vendor, we hold things back. We already give away 80% of the raw ingredients for this anyways. I can link you to a few posts on how commercial open source works if you'd like, but I'm not sure source distribution should affect you here. It's a way of bundling and setting up notebooks, model training etc.. Beyond that, we plan on allowing people to run SKIL CE wherever they want.

Ultimately, you can think of it as downloading AWS and running it locally. It's no different than a hosted service you can download on your laptop.

Expecting a for profit company to blindly give things away is the equivalent of asking me not to pay my developers. We are not a charity. If you don't expect AWS to give you free compute till it hurts, you shouldn't expect us to do the same. We are as clear about that as we can be.

**Comment by ghisvail** [comment]
Don't get me wrong, I am not questioning your business model despite what the tone of your reply strongly suggests.

**Comment by agibsonccc** [comment]
@ghisvail right so there's a few things here.

1. Some expectations around what the intentions for SKIL CE
2. The real use cases for the source.

I'm open to feedback with the proper understanding, but asking for the source without justifying why and calling it useless without isn't the right way to approach this discussion. 

If there's something we could be communicating better here let me know. I was serious about not understanding the difference though. What difference does having the source achieve for you on a discussion about running on debian? Was it because you planned on building deb archives with it?

If it was to be in accordance with their policies that makes sense. If not, we will be supporting deb packaging soon anyways.

**Comment by ghisvail** [comment]
> I'm open to feedback with the proper understanding, but asking for the source without justifying why and calling it useless without isn't the right way to approach this discussion.

I wrongly assumed the business model around SKIL-CE would be open-core instead of freemium, hence the request.

I don't recall calling the software "useless", just mentioned it might not suit **my** needs. You made yourself clear I touched a raw nerve by asking for the availability of the source, but you really don't have to fabricate statements to make me look bad. I made an honest mistake, and I shall apologize for it.

**Comment by agibsonccc** [comment]
@ghisvail apologies! We'll make sure to comment on that. The "open core" part is dl4j and the associated libs. That's partially on us to confirm. Yes I jumped to conclusions but I wanted to be clear where the boundaries were. The "closed wrapper" itself is SKIL.  Thanks for clarifying! Sorry it's just easy for us to assume folks want everything (this is *very* common in open source, I see it daily)

**Comment by wmeddie** [comment]
The docker container is out now at https://hub.docker.com/r/skymindops/skil-ce/ but we will have a .deb build as soon as time permits and I'll close this issue.

**Comment by ShamsUlAzeem** [comment]
We have a debian distro here at the download page: https://skymind.ai/download
