### ISSUE TITLE
How to scale a model/REST API?

### ISSUE THREAD

**Issue by akinmail** [SkymindIO/SKIL-CE#9]
Using the Community Edition, i found out that the api is being setup and managed by the SKIL server. For production, one of our requirements is to be able to scale out instances of our API, for example if suddenly 100 million request start coming into one Rest API instance vs multiple instances, the latter obviously would have better uptime.

Is there a way to configure SKIL to deploy multiple instances of the rest api, even though they might be using the same trained model? Or replicate the same model across multiple API instance.

Hope that makes sense.

**Comment by tomthetrainer** [comment]
@akinmail 

Thanks for the issue.

I am not sure of the status of an automatic scaleout. Therefore I am labelling this as an enhancement request. 

@wmeddie do you have anything to add?

**Comment by wmeddie** [comment]
Sorry for the delayed response due to the holidays.

SKIL CE only supports a single node configuration but our full supported version can support a large number of SKIL nodes in a cluster configuration.

When you import a model into a Deployment you can define (and very soon also update) the Scale parameter.  This parameter works like Heroku's `ps:scale` parameter and SKIL will make sure there are that number of model server processes running and load balance between them.  Every node in the cluster is able to act like a load balancer for deployments so for high availability you will want two point your clients to use at least two SKIL nodes.

It's also worth noting that our model server also load balances requests over GPUs and comes with auto-batching built-in so it'll queue up requests in a batch while it waits for CPU or GPU resources to become available so depending on your workload you might need a smaller scale than you might expect.

**Comment by tomthetrainer** [comment]
That reply looks complete so I am going to close this.
